traveling.cpp File Reference
traveling.cpp File Reference
#include <iostream>
#include <stdio.h>
#include <stdlib.h>
#include <algorithm>
#include "middleearth.h"
Functions
float computeDistance (MiddleEarth &me, string start, vector< string > dests)
Computes the total distance of a given path.
void printRoute (string start, vector< string > dests)
Prints the route for a given starting position and vector of destinations.
int main (int argc, char **argv)
Does a brute force traveling salesman calculation.
Function Documentation
float computeDistance (MiddleEarth & me, string start, vector< string > dests)
Computes the total distance of a given path.
Returns:
Returns the sum of the distances as a float.
Parameters:
me The generated world.
start A string containing the starting location.
dests A vector of all the destinations to travel to in order.
References MiddleEarth::getDistance().
Referenced by main().
int main (int argc, char ** argv)
Does a brute force traveling salesman calculation.
Returns:
0.
Parameters:
argc should be 6.
argv Gets the height, width, number of cities, seed, and itenerary size from command line parameters.
Generate the world given the command line parameters and store this world in me.
< The generated world
< The generated itinerary
< The first element in the itinerary is the starting position, which is removed
< final will hold the solution to the traveling salesman problem
< min will hold the total distance of the solution to the traveling salesman problem
< tdist will hold the total distance of a given permutation of the itinerary to be compared with min
Permutate through all combinations of the itinerary, if a given permuation has a distance shorter than min, set that permutation as the new min.
Print out the value and itinerary of the calculated shortest distance.
References computeDistance(), MiddleEarth::getItinerary(), and printRoute().
void printRoute (string start, vector< string > dests)
Prints the route for a given starting position and vector of destinations.
Parameters:
start The starting position.
dests A vector of the destinations to print in order.
Referenced by main().